extends Node

var elder_memory = [	"Remember when we would sit on the porch and watch the fireflies? Those were the good old days.",	"I have so many happy memories from my youth. I hope the young ones today are making memories too.",	"I still miss my dear husband. We used to take walks in the orchard and pick apples together.",	"I remember playing with my grandkids in the orchard. They loved running through the rows of trees.",	"I have fond memories of baking apple pies with my mother. She always used the freshest apples from our orchard."]

var elder_nostalgia = [	"I long for the days when things were simpler. I miss the taste of fresh apple pie made with love.",	"I miss the days when we would sit outside and watch the stars. The world is just so noisy now.",	"I miss the times when we would play games and laugh with our friends and family. Those were the days.",	"I miss the days when we would gather together and share stories. I hope the young ones keep that tradition alive.",	"I miss the sound of the birds singing in the morning, and the smell of fresh baked apple pie."]

var elder_pie = [	"I just love a warm slice of apple pie. It brings back so many happy memories.",	"Apple pie is my absolute favorite. I could eat it every day and never tire of it.",	"I just baked a fresh apple pie. The smell of it baking in the oven is heavenly.",	"I always add a special ingredient to my apple pie that makes it extra delicious. Can you guess what it is?",	"I love to make apple pie from scratch. There's just something special about making it with your own two hands."]

var elder_love = [	"I am so grateful for the love in my life. It brings me so much joy and happiness.",	"I just love spending time with my family. They bring so much love and light into my life.",	"I love to see the love between couples, it's just so beautiful and heartwarming.",	"I love to see the love between parents and their children. It's just so pure and unconditional.",	"I believe that love is the key to happiness. It has brought so much joy and happiness into my life."]

var elder_hope = [	"I have hope for a better future. I believe that we can make the world a better place.",	"I have hope that the orchard will flourish again. We just need to take care of it and give it love.",	"I have hope that the next generation will continue to make memories and create a better world.",	"I have hope that we will continue to make progress and create a brighter future for all.",	"I have hope that we will find a way to bring the orchard back to its former glory."]
