extends Node


var hivemind_communication = [    "The Hive Mind is a system of communication that allows all Bzls to work together in unity. #HiveMind",    "Coordination is key to the success of the Hive Mind. All Bzls must work together to achieve our goals. #Unity",    "The Hive Mind is a network of connected Bzls, sharing information and working together for the good of the hive. #Cooperation",    "The Hive Mind is the pulse of the hive, connecting all Bzls and ensuring that the hive runs smoothly. #Order",    "The Hive Mind is a source of strength for the Bzls, providing a unified voice and strategy for our future. #Strategy"]

var hivemind_coordination = [    "The Hive Mind coordinates the actions of all Bzls, ensuring that every job is completed efficiently. #Efficiency",    "Coordination is the key to the success of the Hive Mind. All Bzls must work together to achieve our goals. #Success",    "The Hive Mind is a network of connected Bzls, working together to ensure that the hive runs smoothly. #Unity",    "The Hive Mind is the pulse of the hive, connecting all Bzls and ensuring that the hive runs efficiently. #Order",    "The Hive Mind is a source of strength for the Bzls, providing a unified voice and strategy for our future. #Strength"]

var hivemind_unity = [    "The Hive Mind is a symbol of unity for the Bzls. We work together for the good of the hive. #Unity",    "The Hive Mind brings all Bzls together, working in harmony for the success of the hive. #Harmony",    "The Hive Mind is a source of strength for the Bzls, providing a unified voice for our future. #Strength",    "The Hive Mind is the pulse of the hive, connecting all Bzls and ensuring that the hive runs smoothly. #Connection",    "The Hive Mind is a network of connected Bzls, working together to achieve our goals. #Cooperation"]

var hivemind_order = [    "The Hive Mind ensures that the hive runs smoothly, with all Bzls working together in harmony. #Harmony",    "Order is key to the success of the Hive Mind. All Bzls must work together to achieve our goals. #Success",    "The Hive Mind is a source of strength for the Bzls, providing a unified voice and strategy for our future. #Strength",    "The Hive Mind is the pulse of the hive, connecting all Bzls and ensuring that the hive runs efficiently. #Efficiency",    "The Hive Mind is a network of connected Bzls, working together to ensure that the hive runs smoothly. #Unity"]

var hivemind_strategy = [    "The Hive Mind provides a unified voice and strategy for the future of the hive. #Future",    "The Hive Mind is a source of strength for the Bzls, ensuring that we have a clear strategy for success. #Success",    "The Hive Mind coordinates the actions of all Bzls, ensuring that every job is completed efficiently. #Efficiency",    "The Hive Mind is the pulse of the hive, connecting all Bzls and ensuring that the hive runs smoothly. #Order",    "The Hive Mind is a network of connected Bzls, working together to achieve our goals!"]
